---
ios1:
  hostname: ios1
  groups:
    - ios

ios2:
  hostname: ios2
  groups:
    - ios

junos1:
  hostname: junos1
  groups:
    - junos
    
junos2:
  hostname: junos2
  groups:
    - junos

eos1:
  hostname: eos1
  groups:
    - eos

eos2:
  hostname: eos2
  groups:
    - eos

ssg1:
  hostname: ssg1
  groups:
    - ssg

ssg2:
  hostname: ssg2
  groups:
    - ssg
